### ISSUE TITLE
msw test breaking

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/react-workshop-app#45]
@kettanaito, after upgrading msw, we're getting this test failure:

```
 FAIL  src/__tests__/index.js
  ● Test suite failed to run

    Error: Failed to restore patched modules: no patches found. Did you forget to run ".apply()"?

      36 |
      37 | beforeAll(() => server.listen(backend))
    > 38 | afterAll(() => server.close())
         |                       ^
      39 | afterEach(() => server.resetHandlers())
      40 |

      at Object.restore (node_modules/@mswjs/interceptors/src/createInterceptor.ts:83:15)
      at Object.close (node_modules/msw/node/lib/index.js:7690:29)
      at Object.<anonymous> (src/setup-tests.tsx:38:23)
```

I've dug a little bit but I'm not sure what's changed and why this is happening. Any ideas?

**Comment by kettanaito** [comment]
Hey. Looks like @mswjs/interceptors thinks the underlying MSW code is old. Need to debug the dependency tree to see what's the problem. I Will update here with the findings.

**Comment by kettanaito** [comment]
@kentcdodds can you please include the instructions to reproduce this issue?

I'm running the test in isolation (), but getting a different error:

```
  ● regular app

    Cannot find module '@kentcdodds/react-workshop-app/server' from 'example/react-fundamentals/src/backend.js'

    Require stack:
      example/react-fundamentals/src/backend.js
      src/__tests__/index.js

  ● isolated page

    TypeError: Cannot read property 'map' of undefined

      39 |   handlers: Array<RequestHandler>
      40 | }): SetupServerApi | SetupWorkerApi {
    > 41 |   const enhancedHandlers = handlers.map(handler => {
         |                                     ^
      42 |     // @ts-expect-error it's protected but.....
      43 |     const originalResolver = handler.resolver
      44 |     const enhancedResolver: Parameters<typeof rest.get>[1] = async (

      at setup (src/server.tsx:41:37)
      at makeKCDWorkshopApp (src/index.tsx:75:20)
      at Object.<anonymous> (src/__tests__/index.js:90:3)
```

**Comment by kentcdodds** [comment]
Thanks for looking into it. This should get things reproducing for you:

```
git clone https://github.com/kentcdodds/react-workshop-app.git
cd ./react-workshop-app
npm run setup
```

**Comment by kettanaito** [comment]
The culprit seems to be the scope in which `cleanupFns` variable exists:

https://github.com/mswjs/interceptors/blob/ae27f7466b66340ab5bea1175b3c152c235b08d0/src/createInterceptor.ts#L68

During the test setup you can see how `cleanupFns` suddenly becomes empty between `.listen` and `.close`:

```
  console.log
    [setup-tests] beforeAll

      at Object.<anonymous> (src/setup-tests.tsx:38:10)

  console.log
    // These cleanup functions will be called in the "close" ("restore") phase to revert patches.
    [createInterceptor] apply { cleanupFns: [ [Function], [Function] ] }

      at Object.apply (node_modules/@mswjs/interceptors/src/createInterceptor.ts:77:15)

  console.log
    [setup-tests] afterAll

      at Object.<anonymous> (src/setup-tests.tsx:54:11)

  console.log
    [createInterceptor] restore { cleanupFns: [] }
```

The functions cascade is the following:

- [setupServer()](https://github.com/mswjs/msw/blob/c235c6c5cf60e5ac85fd997e7ebacd6579e6ee46/src/node/createSetupServer.ts#L50)
- [server.listen()](https://github.com/mswjs/msw/blob/c235c6c5cf60e5ac85fd997e7ebacd6579e6ee46/src/node/createSetupServer.ts#L164)
  - [interceptor.apply()](https://github.com/mswjs/interceptors/blob/ae27f7466b66340ab5bea1175b3c152c235b08d0/src/createInterceptor.ts#L71-L75)
- [server.close()](https://github.com/mswjs/msw/blob/c235c6c5cf60e5ac85fd997e7ebacd6579e6ee46/src/node/createSetupServer.ts#L202)
  - [interceptor.restore()](https://github.com/mswjs/interceptors/blob/ae27f7466b66340ab5bea1175b3c152c235b08d0/src/createInterceptor.ts#L79-L89)

Moving the `cleanupFns` outside the `createInterceptor` function makes the test pass, but I'm not sure I understand the `cleanupFns` suddenly becoming an empty array. It's like `server.listen` and `server.close` create _separate_ closures, re-evaluating `createInterceptor` and its internal `cleanupFns` variable. But that shouldn't be the case, given that `createInterceptor` is called once on the parent level of `setupServer`. 

@kentcdodds, may I ask for your advice on this?

**Comment by kentcdodds** [comment]
I figured it out! Sorry to make you spend time on this. It turns out these tests run the same code that runs when the app starts up and that includes calling `startWorker` 🤦 So we were calling `createInterceptor` twice which I guess is the issue. Here's the fix: https://github.com/kentcdodds/react-workshop-app/commit/a204e5d453e9180629f527b7fe74cd175626cd83

Thanks for your help!

**Comment by kettanaito** [comment]
That's a twist :D I was expecting an issue with scopes. Thank you for figuring that out, Kent.
